### ISSUE TITLE
Another memory leak

### ISSUE THREAD

**Issue by fsfod** [raptorjit/raptorjit#185] opened 2018-08-09 21:53 UTC
Running our [luacheck ](https://github.com/softdevteam/lua_benchmarking/blob/master/benchmarks/luacheck/bench.lua) benchmark with "simplerunner.lua --inprocess -b luacheck -c 100" toward the 50th iteration it starts leaking tons of memory. This benchmark also cause tons traces to be created and flushes them often as well.

**Comment by lukego** [comment] 2018-08-12 09:48
Thanks for reporting this. I made a [small script](https://gist.github.com/1d27532d30a47bec4282100379346388) for `git bisect` to detect the memory leak. It says that it was introduced in 9df12380934d24d888aaa4ac9e51dba0929771cf.

This is interesting in that 9df12380934d24d888aaa4ac9e51dba0929771cf is a merge commit. My interpretation is that the leak is not due to one single change but rather to merging these commits:

- 43691e0 reusevm: Update generated code
- ad02215 Merge branch 'raptorjit/master' into fix-alloc
- d371db6 lj_state.c: Fix dealloc to match
- bc57ceb lj_state.c: Fix bug in allocation of IR buffer

with these commits:

- 6d9b473 Merge #140 branch 'vmprofile-v4' into integrate
- 5cf2076 Merge #120 branch 'record-blacklisted-functions' into integrate
- 0a33b43 Merge #101 branch 'long-running-stable' into integrate
- 4fafb32 Merge #98 branch 'lukego/szirmcode' into integrate
- 520c6d3 Merge #86 branch 'ffi-pointer-difference-div' into integrate
- 5454da8 Merge #79 branch 'unused-bench-param' into integrate
- 34f24ae Merge #81 branch 'gctrace-origin' into integrate
- 88cc35c reusevm: update generated code
- a8b0f32 lj_vmprofile.c: Add assertions with lua_assert
- 0823d96 lj_vmprofile.c: Fix trace number overflow (into bucket 0)
- ae5c6aa vm_x64.dasc: Fixes to ensure g.lasttrace is a trace number
- c1659d9 VMProfile 4.0: File format revision
- 5cac382 lj_vmprofile.c: Fix file header initialization
- 2b89796 vmprofile 3.0 with more information
- bd7266d Track last exited trace (lasttrace) in global_State
- 089c55a lj_obj.h: Explicitly define implicit VM states
- f5d810e lj_record.c: Record IFUNC/IFUNCV the same as FUNC/FUNCV
- ce6fbb4 lj_record.c: Relax heuristic for root trace meeting JIT loop
- a720595 lj_trace.c: Reset hotcount table after flush
- 01dc844 lj_jit.h: Increase HOTCOUNT_MAX and expand HotPenalty.val
- f7212cc lj_trace.c: Clear penalty slot after successful trace
- ad14f45 GCtrace: Make it possible to map between IR and mcode insns
- cf655d9 lj_crecord.c: JIT pointer difference for all element sizes
- fcf7053 check-generated-code.nix: Add more verbosity
- 4aaa844 lj_jit.h: Save 'parent' and 'exitno' fields in GCtrace
- d7fd44e testsuite/bench: Remove PARAM_* for unsupported platforms

Have to take a closer look starting with those first commits that change memory allocation.

**Comment by lukego** [comment] 2018-08-13 09:56
This seems to be a combination of two bugs.

1. The trace table is filling up and the VM is spinning in `trace_flushall()` to try and make more space. This doesn't work due to a bug in tracking how many trace array slots are available. (This is a regression of a problem we have seen before stemming from RaptorJIT wanting to avoid reusing trace numbers to make tracing/profiling across flushes easier.)
2. This spinning in `trace_flushall()` seems to leak memory due to the allocation change introduced with 9df1238.

Fixes coming.

**Comment by lukego** [comment] 2018-08-14 09:44
@fsfod Can you try pulling `master` now that #186 has merged? This should fix the problem. I need to audit the allocations/frees to find potential leaks that might still be lurking but I don't expect that to impact your tests.

**Comment by fsfod** [comment] 2018-08-20 12:33
It still seems to get stuck and allocate tons of memory even with rebuilding from the latest master commit

**Closed** 2018-10-09 15:32 UTC
